language: php

# Test each latest stable PHP versions at: https://www.php.net/downloads.php
php:
  - 5.2
  - 5.3
  - 5.6
  - 7.0
  - 7.1
  - 7.1.32
  - 7.2
  - 7.3
  - 7.4
  - nightly

script: tests/run-tests.sh
